### ISSUE TITLE
unable to search all members

### ISSUE THREAD

**Issue by kaivalya** [Rahul27297/DifferentModel#1]
There is no facility to search/display all members of the society. Please add in dropdown ability to search all members. 

In addition, search works for exact match only and doesn't work for contains. For example, if an email address "abcd@gmail.com" exist and search is performed by "abcd@g" then I get result as no member found. It should display all members containing "abcd@g".

@iamsharduld @Rahul27297

**Comment by tnsdota** [comment]
Done
